### ISSUE TITLE
Do you have its kernel source?

### ISSUE THREAD

**Issue by mxpro2003** [BabQ/android_device_vivo_y67#3]
I can't find its kernel source on the "https://opensource.vivo.com/Project".

And the "mobileOSS@vivo.com" also don't reply my email.

**Comment by mxpro2003** [comment]
After searching the whole github, only one issue was found.
https://github.com/vivo/vivo.github.io/issues/1
Seemly it's what led to the OpenSource of Y81, Y51 and X21(Some old vivo devices).

**Comment by Itsuwarii** [comment]
Hi @mxpro2003 
Sorry, I don't have the kernel source of this device.

**Comment by Itsuwarii** [comment]
As you can see,I used kernel binary in the device tree

**Comment by mxpro2003** [comment]
> Hi @mxpro2003 Sorry, I don't have the kernel source of this device.

What a pity! I am also seaching kernel source of Y69(PD1705_Nougat), which shares same SOC with Y67. Have you tried emailing them? I am thinking whether my email address is banned.

**Comment by mxpro2003** [comment]
> As you can see,I used kernel binary in the device tree

Kernel Source of Y69 may be useful to your work. Compared to Y67's Marshmallow, it is equipped with Android-7(Nougat)

**Comment by Itsuwarii** [comment]
> > Hi @mxpro2003 Sorry, I don't have the kernel source of this device.
> 
> What a pity! I am also seaching kernel source of Y69(PD1705_Nougat), which shares same SOC with Y67. Have you tried emailing them? I am thinking whether my email address is banned.
> 
> By the way, they often put kernel source at path like "/home/compiler/workspace/gphone/MT6750/PD1612/vivo_mtk_ALPS.M0.MP7.V2.10_mt6750_DailyTest_MD/kernel". You can find this at kernel binary.

I send email to 2020Labs@vivo.com ask for the kernel source code of y67 in October 2018, but they haven't replied to me up to now

**Comment by mxpro2003** [comment]
[vivo/vivo.github.io#1](https://github.com/vivo/vivo.github.io/issues/1) 
@succerseng Maybe pushing a issue will be useful? Seemly these guys succceded in this way, even they got the kernel source of Y51, an old device sold in 2015.
But power of one person may not be enough, could you please lend a hand?

**Comment by mxpro2003** [comment]
[vivo/vivo.github.io#1](https://github.com/vivo/vivo.github.io/issues/1) 
@succerseng Maybe pushing a issue will be useful? Seemly these guys succceded in this way, even they got the kernel source of Y51, an old device sold in 2015.

But power of one person may not be enough, could you please lend a hand? Try this to get kernel sources of Y67 and Y69.
